// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Yago Faran",
            "email": "yagofaran@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/technologies": {
            "post": {
                "description": "This endpoint creates a new technology",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technologies"
                ],
                "summary": "creates a new technology",
                "parameters": [
                    {
                        "description": "creation attributes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecases.TechnologyInput"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "usecases.TechnologyInput": {
            "type": "object",
            "properties": {
                "display": {
                    "description": "whether it will be displayed on the skills page",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "tech name",
                    "type": "string",
                    "example": "Go"
                },
                "src": {
                    "description": "tech icon file name",
                    "type": "string",
                    "example": "go.png"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Portfolio server",
	Description:      "This API is designed to improve the management of project and experience information for your portfolio website, ensuring a seamless rendering and effortless updating process. Additionally, it facilitates interaction with Firebase Storage, allowing you to efficiently load and display icons and images, enhancing the overall visual experience of your portfolio.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
