basePath: /api
definitions:
  technologies_domain.Technology:
    properties:
      display:
        type: boolean
      id:
        type: string
      name:
        type: string
      src:
        type: string
    type: object
  usecases.AlterTechnologyDisplayOutput:
    properties:
      display:
        type: boolean
      id:
        type: string
      name:
        type: string
      src:
        type: string
    type: object
  usecases.CreateExperienceInput:
    properties:
      company:
        example: Metacortex
        type: string
      end:
        example: 10/2023
        type: string
      logo:
        example: metacortex.svg
        type: string
      position:
        example: Developer
        type: string
      start:
        example: 01/2023
        type: string
      summary:
        example:
        - Developed 3 apps
        items:
          type: string
        type: array
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
    type: object
  usecases.CreateExperienceOutput:
    properties:
      company:
        example: Metacortex
        type: string
      id:
        example: 6568ee3e7bbf5a6160f444f4
        type: string
      logo:
        example: metacortex.svg
        type: string
      period:
        $ref: '#/definitions/usecases.Period'
      position:
        example: Developer
        type: string
      summary:
        example:
        - Developed 3 apps
        items:
          type: string
        type: array
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
    type: object
  usecases.CreateProjectInput:
    properties:
      description:
        example:
        - lets the user register projects
        items:
          type: string
        type: array
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
      title:
        example: Portfolio App
        type: string
    type: object
  usecases.CreateProjectOutput:
    properties:
      description:
        example:
        - lets the user register projects
        items:
          type: string
        type: array
      display:
        example: true
        type: boolean
      id:
        example: 6568ee3e7bbf5a6160f444f4
        type: string
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
      title:
        example: Portfolio App
        type: string
    type: object
  usecases.ListExperiencesOutput:
    properties:
      company:
        example: Metacortex
        type: string
      id:
        example: 6568ee3e7bbf5a6160f444f4
        type: string
      logo:
        example: metacortex.svg
        type: string
      period:
        $ref: '#/definitions/usecases.Period'
      position:
        example: Developer
        type: string
      summary:
        example:
        - Developed 3 apps
        items:
          type: string
        type: array
      techs:
        items:
          $ref: '#/definitions/technologies_domain.Technology'
        type: array
    type: object
  usecases.ListTechnologiesOutput:
    properties:
      display:
        type: boolean
      id:
        type: string
      name:
        type: string
      src:
        type: string
    type: object
  usecases.Period:
    properties:
      end:
        example: 10/2023
        type: string
      start:
        example: 01/2023
        type: string
    type: object
  usecases.TechnologyInput:
    properties:
      display:
        description: whether it will be displayed on the skills page
        example: true
        type: boolean
      name:
        description: tech name
        example: Go
        type: string
      src:
        description: tech icon file name
        example: go.png
        type: string
    type: object
  usecases.TechnologyOutput:
    properties:
      display:
        type: boolean
      id:
        type: string
      name:
        type: string
      src:
        type: string
    type: object
  usecases.UpdateExperienceInput:
    properties:
      company:
        example: Metacortex
        type: string
      end:
        example: 10/2023
        type: string
      id:
        example: 6568ed9d59e4487ccb66c757
        type: string
      logo:
        example: metacortex.svg
        type: string
      position:
        example: Developer
        type: string
      start:
        example: 01/2023
        type: string
      summary:
        example:
        - Developed 3 apps
        items:
          type: string
        type: array
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
    type: object
  usecases.UpdateExperienceOutput:
    properties:
      company:
        example: Metacortex
        type: string
      id:
        example: 6568ee3e7bbf5a6160f444f4
        type: string
      logo:
        example: metacortex.svg
        type: string
      period:
        $ref: '#/definitions/usecases.Period'
      position:
        example: Developer
        type: string
      summary:
        example:
        - Developed 3 apps
        items:
          type: string
        type: array
      techs:
        example:
        - 6568ed9d59e4487ccb66c757
        items:
          type: string
        type: array
    type: object
info:
  contact:
    email: yagofaran@gmail.com
    name: Yago Faran
  description: This API is designed to improve the management of project and experience
    information for your portfolio website, ensuring a seamless rendering and effortless
    updating process. Additionally, it facilitates interaction with Firebase Storage,
    allowing you to efficiently load and display icons and images, enhancing the overall
    visual experience of your portfolio.
  license:
    name: MIT
  title: Portfolio server
  version: "1.0"
paths:
  /experiences:
    get:
      description: This endpoint lists all registered experiences
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.ListExperiencesOutput'
            type: array
      summary: List Experiences
      tags:
      - Experiences
    patch:
      consumes:
      - application/json
      description: This endpoint can alter any experience field
      parameters:
      - description: creation attributes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecases.UpdateExperienceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.UpdateExperienceOutput'
      summary: Updates experience
      tags:
      - Experiences
    post:
      consumes:
      - application/json
      description: This endpoint creates an experience
      parameters:
      - description: creation attributes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecases.CreateExperienceInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecases.CreateExperienceOutput'
      summary: Creates an experience
      tags:
      - Experiences
  /images/{name}:
    get:
      description: This endpoint returns the image file by its name
      parameters:
      - description: File name
        in: path
        name: name
        required: true
        type: string
      produces:
      - image/png
      - image/jpeg
      - image/svg+xml
      - image/gif
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get image file
      tags:
      - Images
  /images/icons/{name}:
    get:
      description: This endpoint returns the icon file by its name
      parameters:
      - description: File name
        in: path
        name: name
        required: true
        type: string
      produces:
      - image/png
      - image/jpeg
      - image/svg+xml
      - image/gif
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get icon file
      tags:
      - Images
  /projects:
    post:
      consumes:
      - application/json
      description: This endpoint creates a project
      parameters:
      - description: creation attributes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecases.CreateProjectInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecases.CreateProjectOutput'
      summary: Creates a project
      tags:
      - Projects
  /technologies:
    get:
      description: 'This endpoint lists all technologies that are marked as display:
        true'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/usecases.ListTechnologiesOutput'
            type: array
      summary: List Technologies
      tags:
      - Technologies
    post:
      consumes:
      - application/json
      description: This endpoint creates a new technology
      parameters:
      - description: creation attributes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecases.TechnologyInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/usecases.TechnologyOutput'
      summary: Creates a new technology
      tags:
      - Technologies
  /technologies/{id}:
    patch:
      description: This endpoint alters a technology's display parameter
      parameters:
      - description: Technology Id
        in: path
        name: id
        required: true
        type: string
      - description: display value to be modified to
        enum:
        - "true"
        - "false"
        in: query
        name: display
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AlterTechnologyDisplayOutput'
      summary: Alters technology display
      tags:
      - Technologies
swagger: "2.0"
